version: '3.7'

services:
  weather_go:
    container_name: weather_go
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file: .env
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${NODEJS_PORT}

volumes:
  node_modules:

networks:
  default:
    external:
      name: nginx-proxy